"""empty message

Revision ID: 450fc7cfe00f
Revises: 8dae43cf597e
Create Date: 2023-01-29 20:49:23.799919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '450fc7cfe00f'
down_revision = '8dae43cf597e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
